version: "3.8"

networks:
  loki:
    driver: bridge

services:

  gerador-log:
    image: fabricioveronez/gerador-log
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:5000"
    restart: always
    volumes:
      - "./logs/gerador-log:/logs" 
    networks:
      - loki    

  loki:
    image: grafana/loki:3.2.0
    ports:
      - "3100:3100"
    command: 
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true
    networks:
      - loki

  promtail:
    image: grafana/promtail:3.2.0
    command: -config.file=/etc/promtail/config.yml
    volumes: 
      - "./logs/gerador-log:/logs/gerador-log"
      - "/var/log:/logs/syslogs"
      - "./config/promtail.yaml:/etc/promtail/config.yml" 
      - "./config/position:/position"   
    depends_on: 
      - loki
      - gerador-log    
    networks:
      - loki
    ports:
      - 9080:9080
  grafana:
    image: grafana/grafana:11.2.1
    ports:
      - "3000:3000"
    depends_on: 
      - loki              
    networks:
      - loki